export type Track = {
  id: string;
  title: string;
  artist: string;
  genre: string;
  artworkAsset: string;
  audioAsset: string;
};

export const tracks: Track[] = [
  {
    id: 'midnight-orbit',
    title: 'Midnight Orbit',
    artist: 'Nova Vale',
    genre: 'Synthwave',
    artworkAsset: 'src/assets/artwork/midnight-orbit.png',
    audioAsset: 'src/assets/audio/midnight-orbit.mp3',
  },
  {
    id: 'glass-frequency',
    title: 'Glass Frequency',
    artist: 'Mira Sol',
    genre: 'Dream Pop',
    artworkAsset: 'src/assets/artwork/glass-frequency.png',
    audioAsset: 'src/assets/audio/glass-frequency.mp3',
  },
  {
    id: 'afterglow-station',
    title: 'Afterglow Station',
    artist: 'The Quiet Signal',
    genre: 'Indie Electronic',
    artworkAsset: 'src/assets/artwork/afterglow-station.png',
    audioAsset: 'src/assets/audio/afterglow-station.mp3',
  },
  {
    id: 'velvet-static',
    title: 'Velvet Static',
    artist: 'Lune Circuit',
    genre: 'Alt R&B',
    artworkAsset: 'src/assets/artwork/velvet-static.png',
    audioAsset: 'src/assets/audio/velvet-static.mp3',
  },
  {
    id: 'neon-rain',
    title: 'Neon Rain',
    artist: 'Aria North',
    genre: 'Future Garage',
    artworkAsset: 'src/assets/artwork/neon-rain.png',
    audioAsset: 'src/assets/audio/neon-rain.mp3',
  },
  {
    id: 'silver-tide',
    title: 'Silver Tide',
    artist: 'Kai Motion',
    genre: 'Chillwave',
    artworkAsset: 'src/assets/artwork/silver-tide.png',
    audioAsset: 'src/assets/audio/silver-tide.mp3',
  },
  {
    id: 'slow-bloom',
    title: 'Slow Bloom',
    artist: 'Iris Den',
    genre: 'Lo-fi',
    artworkAsset: 'src/assets/artwork/slow-bloom.png',
    audioAsset: 'src/assets/audio/slow-bloom.mp3',
  },
  {
    id: 'city-underwater',
    title: 'City Underwater',
    artist: 'Echo Prism',
    genre: 'Ambient Pop',
    artworkAsset: 'src/assets/artwork/city-underwater.png',
    audioAsset: 'src/assets/audio/city-underwater.mp3',
  },
  {
    id: 'opal-drive',
    title: 'Opal Drive',
    artist: 'Sable East',
    genre: 'House',
    artworkAsset: 'src/assets/artwork/opal-drive.png',
    audioAsset: 'src/assets/audio/opal-drive.mp3',
  },
  {
    id: 'soft-velocity',
    title: 'Soft Velocity',
    artist: 'Milo Vex',
    genre: 'Electropop',
    artworkAsset: 'src/assets/artwork/soft-velocity.png',
    audioAsset: 'src/assets/audio/soft-velocity.mp3',
  },
  {
    id: 'blue-hour-tape',
    title: 'Blue Hour Tape',
    artist: 'June Reverie',
    genre: 'Bedroom Pop',
    artworkAsset: 'src/assets/artwork/blue-hour-tape.png',
    audioAsset: 'src/assets/audio/blue-hour-tape.mp3',
  },
  {
    id: 'gravity-lounge',
    title: 'Gravity Lounge',
    artist: 'Orion Bloom',
    genre: 'Nu Jazz',
    artworkAsset: 'src/assets/artwork/gravity-lounge.png',
    audioAsset: 'src/assets/audio/gravity-lounge.mp3',
  },
  {
    id: 'violet-air',
    title: 'Violet Air',
    artist: 'Mika Trace',
    genre: 'Hyperpop',
    artworkAsset: 'src/assets/artwork/violet-air.png',
    audioAsset: 'src/assets/audio/violet-air.mp3',
  },
  {
    id: 'hologram-heart',
    title: 'Hologram Heart',
    artist: 'Dawn Relay',
    genre: 'Pop',
    artworkAsset: 'src/assets/artwork/hologram-heart.png',
    audioAsset: 'src/assets/audio/hologram-heart.mp3',
  },
  {
    id: 'blacklight-memory',
    title: 'Blacklight Memory',
    artist: 'Riven Coast',
    genre: 'Post Rock',
    artworkAsset: 'src/assets/artwork/blacklight-memory.png',
    audioAsset: 'src/assets/audio/blacklight-memory.mp3',
  },
  {
    id: 'electric-mist',
    title: 'Electric Mist',
    artist: 'Solace Club',
    genre: 'Downtempo',
    artworkAsset: 'src/assets/artwork/electric-mist.png',
    audioAsset: 'src/assets/audio/electric-mist.mp3',
  },
  {
    id: 'crystal-detour',
    title: 'Crystal Detour',
    artist: 'Vera Light',
    genre: 'Disco Pop',
    artworkAsset: 'src/assets/artwork/crystal-detour.png',
    audioAsset: 'src/assets/audio/crystal-detour.mp3',
  },
  {
    id: 'starlit-basement',
    title: 'Starlit Basement',
    artist: 'Noah Vale',
    genre: 'Alternative',
    artworkAsset: 'src/assets/artwork/starlit-basement.png',
    audioAsset: 'src/assets/audio/starlit-basement.mp3',
  },
  {
    id: 'aurora-thread',
    title: 'Aurora Thread',
    artist: 'The Lucid Hours',
    genre: 'Ambient',
    artworkAsset: 'src/assets/artwork/aurora-thread.png',
    audioAsset: 'src/assets/audio/aurora-thread.mp3',
  },
  {
    id: 'final-echo',
    title: 'Final Echo',
    artist: 'Nyla Shore',
    genre: 'Cinematic Electronic',
    artworkAsset: 'src/assets/artwork/final-echo.png',
    audioAsset: 'src/assets/audio/final-echo.mp3',
  },
];
